name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run unit tests
        run: ./gradlew test
      - name: Build release
        run: ./gradlew -Prelease fatJar
      - name: Get current timestamp for release
        id: date
        run: echo "DATE=$(date --utc +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/1PasswordSessionAnalyzerForBurp-main-*.jar
          omitBody: true
          omitName: true
          tag: release-${{ steps.date.outputs.DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
