name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run unit tests
        run: ./gradlew test
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Build release
        run: ./gradlew -Prelease fatJar
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Get current timestamp for release
        id: date
        run: echo "DATE=$(date --utc +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/1PasswordSessionAnalyzerForBurp-main-*.jar
          omitBody: true
          omitName: true
          tag: release-${{ steps.date.outputs.DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
