name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew -Prelease fatJar
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/1PasswordSessionAnalyzerForBurp-main-*.jar
          omitBody: yes
          commit: ${GITHUB_SHA}
          token: ${{ secrets.GITHUB_TOKEN }}
